name: Publish Package to PyPI with poetry

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[stable]')"
    steps:
      - uses: actions/checkout@master
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.2
        with:
          pypi_token: ${{ secrets.pypi_password }}